name: travelar
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_spinkit: "^4.1.2"
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  provider: ^4.0.5
  google_sign_in:
  url_launcher: ^5.4.5
  image_picker: ^0.6.6+1
  path:
  uuid: ^2.0.4
  firebase_storage: ^3.1.5
  font_awesome_flutter:
  carousel_pro: ^1.0.0
  bottom_navy_bar: ^5.4.0
  google_maps_flutter:
  latlong: ^0.6.1
  flutter_rating_bar:
  shared_preferences: ^0.4.3
  geolocator:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/travelAR_logo.png
    - assets/weather/
    - assets/icons/ 